<html>
<head>
<title>1C:Франчайзи "ЛОГО"</title>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<meta name="keywords" content="1С:Предприятие 8.0, фирма 1С, Конфигуратор, конфигурация, прикладное решение, управление торговлей, разработка, обучение, статьи, новости">
<meta name="description" content="Система программ 1С:Предприятие 8.0 включает в себя платформу и прикладные решения, разработанные на ее основе, для автоматизации деятельности организаций и частных лиц. Здесь вы найдете последние новости по 1С:Предприятию 8.0, статьи, информацию о прикладных решениях.">
<link href="/fran_style.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>
</head>

<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">
<table width="100%" height="100%"  border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="70" bgcolor="#FFFFCC" style="border-bottom: solid #996600 1px;">
	   <a href="/"><img src="/images/top_logo.gif" width="180" height="70" border="0"></a></td>
    <td height="70" bgcolor="#FFFFCC" style="border-bottom: solid #996600 1px;"><table width="100%" height="70"  border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td background="/images/top_backgroung.gif" bgcolor="#FFFF99"><div align="center"><img src="/images/banner.gif" width="468" height="60"></div></td>
        <td width="103" bgcolor="#FFFF99"><a href="http://www.1c.ru"><img src="/images/top_logo_fran.gif" width="103" height="70" border="0"></a></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td width="179" align="left" valign="top" bgcolor="#FFFF99" style="border-right: solid #996600 1px;">
    <table width="170" border="0" align="center" cellpadding="2" cellspacing="1" bgcolor="#996600" style="margin-top:5px;">
      <tr>
        <td bgcolor="#FFFFCC"><a href="/" class="menu">Главная</a></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><a href="/services/" class="menu">Услуги</a></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC" class="menu"><a href="/products/" class="menu">1C:Предприятие
            8.0 </a></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="http://www.v8.1c.ru/buhv8/" class="menu_small">1C:Бухгалерия
              8.0 </a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="http://www.v8.1c.ru/trade/" class="menu_small">1С:Управление <br>
      торговлей 8.0</a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="http://www.v8.1c.ru/hrm/" class="menu_small">1С:Зарплата <br>
      и Управление <br>
      Персоналом 8.0</a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="http://www.v8.1c.ru/enterprise/" class="menu_small">1С:Управление
              производственным предприятием 8.0</a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><span class="menu"><a href="http://www.1c.ru/rus/products/1c/predpr/" class="menu">1C:Предприятие
          7.7</a></span></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><a href="/about/" class="menu style1">О компании</a></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="/about/status.shtml" class="menu_small">Наши статусы </a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="/news/" class="menu_small">Новости</a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="/pressreleases/" class="menu_small">Пресс-релизы</a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="/publications/" class="menu_small">Публикации в прессе</a></div></td>
      </tr>	  	  
      <tr>
        <td bgcolor="#FFFFCC"><div style="margin-left:15px;"><a href="/about/contacts.shtml" class="menu_small">Контакты</a></div></td>
      </tr>	  
      <tr>
        <td bgcolor="#FFFFCC" class="menu_small"><div style="margin-left:15px;"><a href="/about/vacancy.shtml" class="menu_small">Вакансии</a></div></td>
      </tr>
      <tr>
        <td bgcolor="#FFFFCC" class="menu_small"><a href="http://www.appp.ru/pressa/5-0.htm" class="menu style1">Почему
            лицензионное? </a></td>
      </tr>
    </table>      
    <div align="center">
    <form name="form1" method="post" action="">
      <select name="menu1" onChange="MM_jumpMenu('parent',this,0)" style="width:170px; height:15px; border-color:#996600; color:#882200; background-color:#FFFBE6; font-size:9px; margin:0px; padding:0px;">
        <option selected>Другие сайты "1С"</option>
        <option value="http://www.1c.ru">www.1c.ru</option>
        <option value="http://www.v8.1c.ru">1C:Предприятие 8.0</option>
        <option value="http://www.buh.1c.ru">БУХ.1С</option>
        <option value="http://www.games.1c.ru">1C:Мультимедиа</option>
        <option value="http://dist.1c.ru/">1C:Дистрибьюция</option>
      </select>
    </form>
	</div>
    </td>
    <td align="left" valign="top" bgcolor="#FFFFFF">

<!-- Конец верхней части шаблона. После редактирования шаблона необходимо скопировать 
в буфер всю чать кода, которая находится выше этого комментария и сохранить ее в файл 
с именем _header.inc /-->